"""Tools for fetching and normalizing member-star kinematics data."""

from .core import (
    GAIA_DR3_SOURCE_NAME,
    GAIA_DR3_SOURCE_REF,
    GAIA_DR3_SOURCE_TABLE,
    GaiaKinematicTarget,
    GaiaTapClient,
    KinematicSource,
    STANDARD_COLUMNS,
    VizierClient,
    build_reference_manifest,
    extract_gaia_targets,
    fetch_gaia_dr3_proper_motions,
    fetch_gaia_dr3_source_rows,
    fetch_registered_sources,
    fetch_source_table,
    gaia_source_ids_from_normalized_row,
    guess_vizier_source_id,
    load_dwarf_rows,
    normalize_gaia_dr3_rows,
    normalize_table,
    read_table_payload,
    write_kinematics_outputs,
    write_reference_manifest,
)
from .registry import KINEMATIC_SOURCES, sources_by_bibcode, sources_by_name

__all__ = [
    "GAIA_DR3_SOURCE_NAME",
    "GAIA_DR3_SOURCE_REF",
    "GAIA_DR3_SOURCE_TABLE",
    "GaiaKinematicTarget",
    "GaiaTapClient",
    "KINEMATIC_SOURCES",
    "KinematicSource",
    "STANDARD_COLUMNS",
    "VizierClient",
    "build_reference_manifest",
    "extract_gaia_targets",
    "fetch_gaia_dr3_proper_motions",
    "fetch_gaia_dr3_source_rows",
    "fetch_registered_sources",
    "fetch_source_table",
    "gaia_source_ids_from_normalized_row",
    "guess_vizier_source_id",
    "load_dwarf_rows",
    "normalize_gaia_dr3_rows",
    "normalize_table",
    "read_table_payload",
    "sources_by_bibcode",
    "sources_by_name",
    "write_kinematics_outputs",
    "write_reference_manifest",
]
