from __future__ import annotations

from .core import KinematicSource


_GEHA2026_SYSTEM_OBJECT_KEYS = {
    "Aqr2": "aquarius_2",
    "Aqr3": "aquarius_3",
    "Boo1": "bootes_1",
    "Boo2": "bootes_2",
    "Boo3": "bootes_3",
    "CB": "coma_berenices_1",
    "CVn1": "canes_venatici_1",
    "CVn2": "canes_venatici_2",
    "Cet3": "cetus_3",
    "Col1": "columba_1",
    "Dra": "draco_1",
    "Dra2": "draco_2",
    "Eri4": "eridanus_4",
    "For": "fornax_1",
    "Herc": "hercules_1",
    "Hyd2": "hydra_2",
    "Leo1": "leo_1",
    "Leo2": "leo_2",
    "Leo4": "leo_4",
    "Leo5": "leo_5",
    "Leo6": "leo_6",
    "Peg3": "pegasus_3",
    "Peg4": "pegasus_4",
    "Pisc2": "pisces_2",
    "Scl": "sculptor_1",
    "Seg1": "segue_1",
    "Seg2": "segue_2",
    "Sext": "sextans_1",
    "Sgr": "sagittarius_1",
    "Tri2": "triangulum_2",
    "UMa1": "ursa_major_1",
    "UMa2": "ursa_major_2",
    "UMi": "ursa_minor_1",
    "W1": "willman_1",
}

_PACE2022_ZENODO_CATALOG_OBJECT_KEYS = (
    "antlia_2",
    "aquarius_2",
    "bootes_1",
    "bootes_2",
    "bootes_3",
    "bootes_4",
    "canes_venatici_1",
    "canes_venatici_2",
    "carina_1",
    "carina_2",
    "carina_3",
    "centaurus_1",
    "cetus_2",
    "columba_1",
    "coma_berenices_1",
    "crater_2",
    "draco_1",
    "draco_2",
    "eridanus_2",
    "fornax_1",
    "grus_1",
    "grus_2",
    "hercules_1",
    "horologium_1",
    "horologium_2",
    "hydra_2",
    "hydrus_1",
    "leo_1",
    "leo_2",
    "leo_4",
    "leo_5",
    "pegasus_3",
    "phoenix_2",
    "pictor_1",
    "pictor_2",
    "reticulum_2",
    "reticulum_3",
    "sagittarius_2",
    "sculptor_1",
    "segue_1",
    "segue_2",
    "sextans_1",
    "triangulum_2",
    "tucana_2",
    "tucana_3",
    "tucana_4",
    "tucana_5",
    "ursa_major_1",
    "ursa_major_2",
    "ursa_minor_1",
    "willman_1",
)
_PACE2022_ZENODO_CATALOG_MEMBERS = {
    object_key: f"share_v2/catalogs/{object_key}.dat"
    for object_key in _PACE2022_ZENODO_CATALOG_OBJECT_KEYS
}


KINEMATIC_SOURCES = [
    KinematicSource(
        name="walker2009_stars",
        bibcode="Walker2009AJ....137.3100W",
        source_id="J/AJ/137/3100/stars",
        source_kind="spectroscopy",
        object_key_column="Target",
        object_key_prefix_map={
            "Car": "carina_1",
            "Fnx": "fornax_1",
            "For": "fornax_1",
            "Scl": "sculptor_1",
            "Sex": "sextans_1",
        },
        columns={
            "star_id": "Target",
            "ra_deg": "RAJ2000",
            "dec_deg": "DEJ2000",
            "vlos_kms": "__HV_",
            "vlos_err_kms": "e__HV_",
            "membership_probability": "Mmb",
        },
        notes="Mean radial velocities and membership probabilities for four classical dSphs.",
    ),
    KinematicSource(
        name="ji2021_antlia2",
        bibcode="Ji2021ApJ...921...32J",
        source_id="J/ApJ/921/32/table4",
        source_kind="spectroscopy",
        object_key="antlia_2",
        columns={
            "star_id": "Gaia",
            "ra_deg": ["_RA.icrs", "RA_ICRS"],
            "dec_deg": ["_DE.icrs", "DE_ICRS"],
            "vlos_kms": "HRV",
            "vlos_err_kms": "e_HRV",
            "pmra_masyr": "pmRA",
            "pmdec_masyr": "pmDE",
            "membership_probability": "Mm",
            "membership_flag": "Bin",
            "feh": "__Fe_H_2",
            "feh_err": "e__Fe_H_2",
        },
        notes="Antlia II S5/Gaia table; includes per-star HRV, Gaia PMs, and membership probability.",
    ),
    KinematicSource(
        name="ji2021_antlia2_aas_iop",
        bibcode="Ji2021ApJ...921...32J",
        source_id="apjac1869t4_mrt",
        source_kind="spectroscopy",
        provider="aas_iop_mrt",
        data_url="https://content.cld.iop.org/journals/0004-637X/921/1/32/revision1/apjac1869t4_mrt.txt",
        table_format="cds",
        object_key="antlia_2",
        columns={
            "star_id": "source_ID",
            "ra_deg": "ra",
            "dec_deg": "dec",
            "vlos_kms": "HRV",
            "vlos_err_kms": "e_HRV",
            "pmra_masyr": "pmra",
            "pmdec_masyr": "pmdec",
            "membership_probability": "pmem",
            "membership_flag": "Bin",
            "feh": "[Fe/H]2",
            "feh_err": "e_[Fe/H]2",
        },
        notes="Publisher MRT version of Ji et al. 2021 table 4 for Antlia II.",
    ),
    KinematicSource(
        name="ji2021_crater2",
        bibcode="Ji2021ApJ...921...32J",
        source_id="J/ApJ/921/32/table5",
        source_kind="spectroscopy",
        object_key="crater_2",
        columns={
            "star_id": "Gaia",
            "ra_deg": ["_RA.icrs", "RA_ICRS"],
            "dec_deg": ["_DE.icrs", "DE_ICRS"],
            "vlos_kms": "HRV",
            "vlos_err_kms": "e_HRV",
            "pmra_masyr": "pmRA",
            "pmdec_masyr": "pmDE",
            "membership_probability": "Mm",
            "membership_flag": "Bin",
            "feh": "__Fe_H_2",
            "feh_err": "e__Fe_H_2",
        },
        notes="Crater II S5/Gaia table; includes per-star HRV, Gaia PMs, and membership probability.",
    ),
    KinematicSource(
        name="ji2021_crater2_aas_iop",
        bibcode="Ji2021ApJ...921...32J",
        source_id="apjac1869t5_mrt",
        source_kind="spectroscopy",
        provider="aas_iop_mrt",
        data_url="https://content.cld.iop.org/journals/0004-637X/921/1/32/revision1/apjac1869t5_mrt.txt",
        table_format="cds",
        object_key="crater_2",
        columns={
            "star_id": "source_ID",
            "ra_deg": "ra",
            "dec_deg": "dec",
            "vlos_kms": "HRV",
            "vlos_err_kms": "e_HRV",
            "pmra_masyr": "pmra",
            "pmdec_masyr": "pmdec",
            "membership_probability": "pmem",
            "membership_flag": "Bin",
            "feh": "[Fe/H]2",
            "feh_err": "e_[Fe/H]2",
        },
        notes="Publisher MRT version of Ji et al. 2021 table 5 for Crater II.",
    ),
    KinematicSource(
        name="li2018_carina23",
        bibcode="Li2018ApJ...857..145L",
        source_id="J/ApJ/857/145/table4",
        source_kind="spectroscopy",
        nearest_object_keys=("carina_2", "carina_3"),
        nearest_max_sep_deg=1.0,
        columns={
            "star_id": "MagLiteS",
            "ra_deg": "RAJ2000",
            "dec_deg": "DEJ2000",
            "vlos_kms": "HRV",
            "vlos_err_kms": "e_HRV",
            "membership_flag": "Mm",
            "feh": "__Fe_H_",
            "feh_err": "e__Fe_H_",
        },
        notes="Carina II/III spectroscopy; membership is a published integer class, not a probability.",
    ),
    KinematicSource(
        name="fritz2019_lmc_satellites",
        bibcode="Fritz2019A&A...623A.129F",
        source_id="J/A+A/623/A129/table2",
        source_kind="spectroscopy",
        object_key_column="ID",
        object_key_prefix_map={
            "col1": "columba_1",
            "phe2": "phoenix_2",
            "ret3": "reticulum_3",
        },
        nearest_object_keys=("columba_1", "phoenix_2", "reticulum_3"),
        nearest_max_sep_deg=2.0,
        columns={
            "star_id": "ID",
            "ra_deg": "RAJ2000",
            "dec_deg": "DEJ2000",
            "vlos_kms": "Vlos",
            "vlos_err_kms": "e_Vlos",
            "pmra_masyr": "pmRA_",
            "pmra_err_masyr": "e_pmRA_",
            "pmdec_masyr": "pmDE",
            "pmdec_err_masyr": "e_pmDE",
            "membership_probability": "Pmember",
            "feh": "__Fe_H_",
            "feh_err": "e__Fe_H_",
        },
        notes="Potential member stars around several LMC satellites; Pmember is 0-1.",
    ),
    KinematicSource(
        name="simon2020_table3",
        bibcode="Simon2020ApJ...892..137S",
        source_id="J/ApJ/892/137/table3",
        source_kind="spectroscopy",
        object_key_column="Gal",
        object_key_map={
            "GruII": "grus_2",
            "TucIV": "tucana_4",
            "TucV": "tucana_5",
        },
        columns={
            "star_id": "DES",
            "ra_deg": "RAJ2000",
            "dec_deg": "DEJ2000",
            "vlos_kms": "HRV",
            "vlos_err_kms": "e_HRV",
            "membership_flag": "Mm",
            "feh": "__Fe_H_",
            "feh_err": "e__Fe_H_",
        },
        notes="IMACS velocity/metallicity measurements for Gru II, Tuc IV, and Tuc V.",
    ),
    KinematicSource(
        name="jenkins2021_table6",
        bibcode="Jenkins2021ApJ...920...92J",
        source_id="J/ApJ/920/92/table6",
        source_kind="spectroscopy",
        object_key_column="ID",
        object_key_prefix_map={
            "Boo1": "bootes_1",
            "BooI": "bootes_1",
            "Leo4": "leo_4",
            "LeoIV": "leo_4",
            "Leo5": "leo_5",
            "LeoV": "leo_5",
        },
        columns={
            "star_id": "ID",
            "ra_deg": "RAJ2000",
            "dec_deg": "DEJ2000",
            "vlos_kms": "RVel",
            "vlos_err_kms": "e_RVel",
            "membership_probability": "MemProb",
            "membership_flag": "Member",
        },
        notes="VLT spectroscopy for Bootes I, Leo IV, and Leo V; includes membership probability.",
    ),
    KinematicSource(
        name="jenkins2021_table6_aas_iop",
        bibcode="Jenkins2021ApJ...920...92J",
        source_id="apjac1353t6_mrt",
        source_kind="spectroscopy",
        provider="aas_iop_mrt",
        data_url="https://content.cld.iop.org/journals/0004-637X/920/2/92/revision1/apjac1353t6_mrt.txt",
        table_format="cds",
        object_key_column="ID",
        object_key_prefix_map={
            "Boo1": "bootes_1",
            "BooI": "bootes_1",
            "Leo4": "leo_4",
            "LeoIV": "leo_4",
            "Leo5": "leo_5",
            "LeoV": "leo_5",
        },
        columns={
            "star_id": "ID",
            "ra_deg": "RAdeg",
            "dec_deg": "DEdeg",
            "vlos_kms": "VHel",
            "vlos_err_kms": "e_VHel",
            "membership_probability": "MemProb",
            "membership_flag": "Member",
        },
        notes="Publisher MRT version of Jenkins et al. 2021 table 6.",
    ),
    KinematicSource(
        name="bruce2023_aquarius2_aas_iop",
        bibcode="Bruce2023ApJ...950..167B",
        source_id="apjacc943t3_mrt",
        source_kind="spectroscopy",
        provider="aas_iop_mrt",
        data_url="https://content.cld.iop.org/journals/0004-637X/950/2/167/revision1/apjacc943t3_mrt.txt",
        table_format="cds",
        object_key="aquarius_2",
        columns={
            "star_id": "Gaia",
            "ra_deg": "RAdeg",
            "dec_deg": "DEdeg",
            "vlos_kms": "Vhelio",
            "vlos_err_kms": "e_Vhelio",
            "membership_flag": "Mem",
            "feh": "[Fe/H]",
            "feh_err": "e_[Fe/H]",
        },
        notes="Publisher MRT table for Aquarius II spectroscopy from Bruce et al. 2023.",
    ),
    KinematicSource(
        name="bruce2023_bootes2_aas_iop",
        bibcode="Bruce2023ApJ...950..167B",
        source_id="apjacc943t4_mrt",
        source_kind="spectroscopy",
        provider="aas_iop_mrt",
        data_url="https://content.cld.iop.org/journals/0004-637X/950/2/167/revision1/apjacc943t4_mrt.txt",
        table_format="cds",
        object_key="bootes_2",
        columns={
            "star_id": "Gaia",
            "ra_deg": "RAdeg",
            "dec_deg": "DEdeg",
            "vlos_kms": "Vhelio",
            "vlos_err_kms": "e_Vhelio",
            "membership_flag": "Mem",
            "feh": "[Fe/H]",
            "feh_err": "e_[Fe/H]",
        },
        notes="Publisher MRT table for Bootes II spectroscopy from Bruce et al. 2023.",
    ),
    KinematicSource(
        name="buttry2022_triangulum2_keck",
        bibcode="Buttry2022MNRAS.514.1706B",
        source_id="J/MNRAS/514/1706/tabled2",
        source_kind="spectroscopy",
        object_key="triangulum_2",
        columns={
            "star_id": ["MIC2016", "KCS2015"],
            "ra_deg": "RA_ICRS",
            "dec_deg": "DE_ICRS",
            "vlos_kms": "vLOS",
            "vlos_err_kms": "e_vLOS",
        },
        notes="Keck/DEIMOS Triangulum II member-star velocities after the published zero-point correction.",
    ),
    KinematicSource(
        name="chiti2023_tucana2_velocities",
        bibcode="Chiti2023AJ....165...55C",
        source_id="J/AJ/165/55/table6",
        source_kind="spectroscopy",
        object_key="tucana_2",
        columns={
            "star_id": "Name",
            "ra_deg": "RAJ2000",
            "dec_deg": "DEJ2000",
            "vlos_kms": "RVel",
            "vlos_err_kms": "e_RVel",
            "membership_flag": "f_RVel",
        },
        notes="Tucana II velocity measurements table.",
    ),
    KinematicSource(
        name="harris2006_smc_red_giants",
        bibcode="Harris2006AJ....131.2514H",
        source_id="J/AJ/131/2514/table2",
        source_kind="spectroscopy",
        object_key="smc",
        columns={
            "star_id": "__HZ2006b_",
            "ra_deg": "RAdeg",
            "dec_deg": "DEJ2000",
            "vlos_kms": "HRVc",
            "vlos_err_kms": "e_RV",
            "membership_flag": "SFlag",
        },
        notes="SMC red giant radial velocities; uses heliocentric velocity corrected column HRVc.",
    ),
    KinematicSource(
        name="kirby2013_segue2_members",
        bibcode="Kirby2013ApJ...770...16K",
        source_id="J/ApJ/770/16/table2",
        source_kind="spectroscopy",
        object_key="segue_2",
        columns={
            "star_id": "SDSS",
            "ra_deg": "_RA",
            "dec_deg": "_DE",
            "vlos_kms": "HRV",
            "vlos_err_kms": "e_HRV",
            "membership_flag": "Mm",
            "feh": "__Fe_H_",
            "feh_err": "e__Fe_H_",
        },
        notes="Segue 2 target stars with membership flag.",
    ),
    KinematicSource(
        name="koposov2018_hydrus1",
        bibcode="Koposov2018MNRAS.479.5343K",
        source_id="J/MNRAS/479/5343/table2",
        source_kind="spectroscopy",
        object_key="hydrus_1",
        columns={
            "star_id": "ID",
            "ra_deg": "RAJ2000",
            "dec_deg": "DEJ2000",
            "vlos_kms": "HRV",
            "vlos_err_kms": "e_HRV",
            "feh": "__Fe_H_",
            "feh_err": "e__Fe_H_",
        },
        notes="Hydrus I individual stellar spectroscopy table.",
    ),
    KinematicSource(
        name="mateo2008_leo1",
        bibcode="Mateo2008ApJ...675..201M",
        source_id="J/ApJ/675/201/table5",
        source_kind="spectroscopy",
        object_key="leo_1",
        columns={
            "star_id": "Seq",
            "ra_deg": "RAJ2000",
            "dec_deg": "DEJ2000",
            "vlos_kms": "HV",
            "membership_flag": "r_HV",
        },
        notes="Leo I target-star radial velocities.",
    ),
    KinematicSource(
        name="simon2011_segue1",
        bibcode="Simon2011ApJ...733...46S",
        source_id="J/ApJ/733/46/table3",
        source_kind="spectroscopy",
        object_key="segue_1",
        columns={
            "star_id": "SDSS",
            "ra_deg": "_RA",
            "dec_deg": "_DE",
            "vlos_kms": "Vel",
            "vlos_err_kms": "e_Vel",
            "membership_flag": "Mm",
        },
        notes="Segue 1 velocity measurements with published membership flag.",
    ),
    KinematicSource(
        name="simon2017_tucana3",
        bibcode="Simon2017ApJ...838...11S",
        source_id="J/ApJ/838/11/table2",
        source_kind="spectroscopy",
        object_key="tucana_3",
        columns={
            "star_id": "DES",
            "ra_deg": "RAJ2000",
            "dec_deg": "DEJ2000",
            "vlos_kms": "HRV",
            "vlos_err_kms": "e_HRV",
            "membership_flag": "Mm",
            "feh": "__Fe_H_",
            "feh_err": "e__Fe_H_",
        },
        notes="Tucana III velocity and metallicity measurements.",
    ),
    KinematicSource(
        name="spencer2017_leo2",
        bibcode="Spencer2017ApJ...836..202S",
        source_id="J/ApJ/836/202/table3",
        source_kind="spectroscopy",
        object_key="leo_2",
        columns={
            "ra_deg": "RAJ2000",
            "dec_deg": "DEJ2000",
            "vlos_kms": "RVel",
            "vlos_err_kms": "e_RVel",
            "membership_flag": "Mm",
            "feh": "__Fe_H_",
            "feh_err": "e__Fe_H_",
        },
        notes="Leo II spectroscopic properties table; no stable star identifier is present in VizieR.",
    ),
    KinematicSource(
        name="spencer2018_ursa_minor",
        bibcode="Spencer2018AJ....156..257S",
        source_id="J/AJ/156/257/table4",
        source_kind="spectroscopy",
        object_key="ursa_minor_1",
        columns={
            "star_id": "ID",
            "ra_deg": "RAJ2000",
            "dec_deg": "DEJ2000",
            "vlos_kms": "RV",
            "vlos_err_kms": "e_RV",
            "membership_flag": "r_RV",
        },
        notes="Ursa Minor weighted velocity means from Spencer et al. 2018.",
    ),
    KinematicSource(
        name="walker2015_reticulum2",
        bibcode="Walker2015ApJ...808..108W",
        source_id="J/ApJ/808/108/table1",
        source_kind="spectroscopy",
        object_key="reticulum_2",
        columns={
            "star_id": "Ret2",
            "ra_deg": "RAJ2000",
            "dec_deg": "DEJ2000",
            "vlos_kms": "Vlos",
            "membership_flag": "Mm_",
            "feh": "__Fe_H_",
        },
        notes="Reticulum II M2FS stellar spectroscopy table.",
    ),
    KinematicSource(
        name="walker2015_draco",
        bibcode="Walker2015MNRAS.448.2717W",
        source_id="J/MNRAS/448/2717/table5",
        source_kind="spectroscopy",
        object_key="draco_1",
        columns={
            "star_id": "All",
            "ra_deg": "RAJ2000",
            "dec_deg": "DEJ2000",
            "vlos_kms": "vlos",
            "vlos_err_kms": "e_vlos",
            "feh": "__Fe_H_",
            "feh_err": "e__Fe_H_",
        },
        notes="Draco Hectochelle weighted means for stars with multiple observations.",
    ),
    KinematicSource(
        name="heiger2024_eridanus4_aas_iop",
        bibcode="Heiger2024ApJ...961..234H",
        source_id="apjad0cf7t3_mrt",
        source_kind="spectroscopy",
        provider="aas_iop_mrt",
        data_url="https://content.cld.iop.org/journals/0004-637X/961/2/234/revision1/apjad0cf7t3_mrt.txt",
        table_format="cds",
        object_key="eridanus_4",
        columns={
            "star_id": "source_id",
            "ra_deg": "RAdeg",
            "dec_deg": "DEdeg",
            "vlos_kms": "vhel",
            "vlos_err_kms": "e_vhel",
            "pmra_masyr": "pmRA",
            "pmra_err_masyr": "e_pmRA",
            "pmdec_masyr": "pmDE",
            "pmdec_err_masyr": "e_pmDE",
            "membership_flag": "Member",
            "feh": "FeH",
            "feh_err": "e_FeH",
        },
        notes="Publisher MRT table for Eridanus IV confirmed members from Heiger et al. 2024.",
    ),
    KinematicSource(
        name="heiger2024_centaurus1_aas_iop",
        bibcode="Heiger2024ApJ...961..234H",
        source_id="apjad0cf7t4_mrt",
        source_kind="spectroscopy",
        provider="aas_iop_mrt",
        data_url="https://content.cld.iop.org/journals/0004-637X/961/2/234/revision1/apjad0cf7t4_mrt.txt",
        table_format="cds",
        object_key="centaurus_1",
        columns={
            "star_id": "source_id",
            "ra_deg": "RAdeg",
            "dec_deg": "DEdeg",
            "vlos_kms": "vhel",
            "vlos_err_kms": "e_vhel",
            "pmra_masyr": "pmRA",
            "pmra_err_masyr": "e_pmRA",
            "pmdec_masyr": "pmDE",
            "pmdec_err_masyr": "e_pmDE",
            "membership_flag": "Member",
            "feh": "FeH",
            "feh_err": "e_FeH",
        },
        notes="Publisher MRT table for Centaurus I confirmed members from Heiger et al. 2024.",
    ),
    KinematicSource(
        name="geha2026_deimos_expanded_aas_iop",
        bibcode="Geha2026ApJ...999..140G",
        source_id="apjae290dt5_mrt",
        source_kind="spectroscopy",
        provider="aas_iop_mrt",
        data_url="https://content.cld.iop.org/journals/0004-637X/999/1/140/revision1/apjae290dt5_mrt.txt",
        table_format="cds",
        object_key_column="System",
        object_key_map=_GEHA2026_SYSTEM_OBJECT_KEYS,
        row_filters={"marz-flag": "1"},
        missing_values=("-999", "-99"),
        columns={
            "star_id": ["Object", "Gaia"],
            "ra_deg": "RAdeg",
            "dec_deg": "DEdeg",
            "vlos_kms": "HRV",
            "vlos_err_kms": "e_HRV",
            "pmra_masyr": "pmRA",
            "pmra_err_masyr": "e_pmRA",
            "pmdec_masyr": "pmDE",
            "pmdec_err_masyr": "e_pmDE",
            "membership_probability": "Pmem",
            "membership_flag": "Pmem-novar",
            "feh": "FeH",
            "feh_err": "e_FeH",
        },
        notes="Publisher MRT Table A5 from the Keck/DEIMOS Stellar Archive, filtered to stellar targets.",
    ),
    KinematicSource(
        name="sandford2026_bootes1_combined_aas_iop",
        bibcode="Sandford2026ApJ...998...47S",
        source_id="apjae2fe5t6_mrt",
        source_kind="spectroscopy",
        provider="aas_iop_mrt",
        data_url="https://content.cld.iop.org/journals/0004-637X/998/1/47/revision1/apjae2fe5t6_mrt.txt",
        table_format="cds",
        object_key="bootes_1",
        columns={
            "star_id": ["GaiaID", "AltID"],
            "ra_deg": "RAdeg",
            "dec_deg": "DEdeg",
            "vlos_kms": "vel-avg",
            "vlos_err_kms": "e_vel-avg",
            "pmra_masyr": "pmRA",
            "pmra_err_masyr": "e_pmRA",
            "pmdec_masyr": "pmDE",
            "pmdec_err_masyr": "e_pmDE",
            "membership_flag": "member",
            "feh": "[Fe/H]avg",
            "feh_err": "e_[Fe/H]avg",
        },
        notes="Publisher MRT Appendix A combined stellar catalog for Bootes I chemodynamics from Sandford et al. 2026.",
    ),
    KinematicSource(
        name="pace2022_dwarf_spheroidal_gaia_edr3_zenodo",
        bibcode="Pace2022ApJ...940..136P",
        source_id="zenodo_14732612_share_v2_catalogs",
        source_kind="proper_motion",
        provider="zenodo_zip",
        data_url="https://zenodo.org/api/records/14732612/files/share_v2.zip/content",
        table_format="commented_header",
        archive_members=_PACE2022_ZENODO_CATALOG_MEMBERS,
        object_key_column="object_key",
        row_min_values={"mem_fixed": 0.1},
        missing_values=("-9", "-9.0"),
        columns={
            "star_id": "source_id",
            "ra_deg": "ra",
            "dec_deg": "dec",
            "pmra_masyr": "pmra",
            "pmra_err_masyr": "pmra_error",
            "pmdec_masyr": "pmdec",
            "pmdec_err_masyr": "pmdec_error",
            "membership_probability": "mem_fixed",
        },
        notes="Zenodo v3 Gaia EDR3 dwarf spheroidal membership catalogs from Pace et al. 2022, filtered to mem_fixed >= 0.1 candidate members.",
    ),
    KinematicSource(
        name="battaglia2022_tucana5_pmem",
        bibcode="Battaglia2022A&A...657A..54B",
        source_id="J/A+A/657/A54/pmem",
        source_kind="proper_motion",
        query_constraints={"Galaxy": "TucanaV"},
        object_key_column="Galaxy",
        object_key_map={"TucV": "tucana_5", "TucanaV": "tucana_5"},
        columns={
            "star_id": "GaiaEDR3",
            "ra_deg": ["_RA.icrs", "RA_ICRS"],
            "dec_deg": ["_DE.icrs", "DE_ICRS"],
            "membership_probability": "Pmemb",
        },
        notes="Gaia EDR3 membership probabilities for Local Group systems; VizieR table does not expose per-star PM components.",
    ),
]


def sources_by_name() -> dict[str, KinematicSource]:
    """Return registered kinematics sources indexed by name.

    Returns
    -------
    dict[str, KinematicSource]
        Registry entries keyed by source name.
    """
    return {source.name: source for source in KINEMATIC_SOURCES}


def sources_by_bibcode() -> dict[str, list[KinematicSource]]:
    """Return registered kinematics sources indexed by ADS bibcode.

    Returns
    -------
    dict[str, list[KinematicSource]]
        Registry entries grouped by source-paper bibcode.
    """
    by_bibcode: dict[str, list[KinematicSource]] = {}
    for source in KINEMATIC_SOURCES:
        by_bibcode.setdefault(source.bibcode, []).append(source)
    return by_bibcode
